title: Matt Fantinel - Web Developer
description: ğŸ•¸ï¸ Front-End Web Developer | ğŸ§™â€â™‚ï¸ Open Sourcerer | ğŸ‘‰ï¸ Bullet List Enthusiast
permalink: /:title/

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://fantinel.dev

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-gzip

paginate: 7
paginate_path: "/blog/page:num/"

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

future: false # Allows us to stage posts
exclude: [README.md, Gemfile, Gemfile.lock, vendor]

sass:
  style: :compressed # You might prefer to minify using :compressed